#!/usr/bin/python3

import argparse
import datetime
from sqlalchemy import desc, or_

import dmt.db as db
import dmt.helpers as helpers
from dmt.BasePageGenerator import BasePageGenerator
import dmt.StatusGenerator as StatusGenerator
import dmt.HierarchyGenerator as HierarchyGenerator

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--dburl', help='database', default=db.MirrorDB.DBURL)
    parser.add_argument('--templatedir', help='template directory', default='templates')
    args = parser.parse_args()
    base = BasePageGenerator(**args.__dict__)

    for cl in (StatusGenerator,HierarchyGenerator,):
        i = cl.Generator(base = base, outfile=cl.OUTFILE)
        i.run()

