#!/usr/bin/python3

import datetime
import urllib.parse

import dmt.db as db
from dmt.Masterlist import Masterlist

MASTERLIST='Mirrors.masterlist'
ARCHIVEKEY = 'Archive'
SERVICE = 'http'

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--archivekey', help='Key for the current archive', default=ARCHIVEKEY)
    parser.add_argument('--origin', help='Label for the origin', default=MASTERLIST)
    parser.add_argument('--masterlist', help='Mirrors.masterlist file', default=MASTERLIST)
    parser.add_argument('--dburl', help='database', default=db.MirrorDB.DBURL)
    args = parser.parse_args()

    masterlist = Masterlist(args.masterlist).entries
    session = db.MirrorDB(args.dburl).session()

    db.update_or_create(session, db.Origin, {}, label=args.origin)
    origin = session.query(db.Origin).filter_by(label = args.origin).first()
    assert(origin is not None)

    for sitename, sitedata in masterlist.items():
        for k in (args.archivekey+"-"+SERVICE, args.archivekey+"-unlisted-"+SERVICE):
            if k in sitedata:
                http_path = sitedata[k]
                break
        else:
            continue

        dbdata = { 'origin_id': origin.id,
                   'http_path': http_path
                 }

        if 'Connect-http' in sitedata:
            up = urllib.parse.urlparse('//'+sitedata['Connect-http'])
            dbdata['http_override_host'] = up.hostname
            dbdata['http_override_port'] = up.port

        db.update_or_create(session, db.Site, dbdata, name=sitename)
        site = session.query(db.Site).filter_by(name = sitename).first()

        provides = sitedata['Provides'] if 'Provides' in sitedata else []
        for alias in provides:
            db.update_or_create(session, db.SiteAlias, {}, name=alias, site_id=site.id)
        for alias in session.query(db.SiteAlias).filter_by(site_id = site.id):
            if alias.name not in provides:
                session.delete(alias)


    for site in session.query(db.Site).filter_by(origin_id = origin.id):
        if site.name not in masterlist:
            session.delete(site)

    session.commit()
