#!/bin/bash

set -e
set -u

BTS_STATE_FILE=".bugs-state.json"
BTS_STATE_AGE="3600"

fullpath=$(readlink -f "$0")
dir=$(dirname "$fullpath")
cd "$dir"

exec 200< "$fullpath"
if ! flock -w 60 -e 200; then
	echo >&1 "Cannot acquire lock"
	exit 1
fi


TARGET="$dir"/htdocs

./import-mirrors
./import-mirrors --origin internal --masterlist internal-mirrors.list
./run-tests
./run-process

./import-mirrors --archivekey Security --dburl postgresql:///mirror-status-security
./import-mirrors --archivekey Security --dburl postgresql:///mirror-status-security --origin internal --masterlist internal-mirrors.list
./run-tests --dburl postgresql:///mirror-status-security
./run-process --dburl postgresql:///mirror-status-security

tmpdir=$(mktemp -d /tmp/mirror-status.XXXXXXXXXX)
trap "rm -r $tmpdir" EXIT

./generate --outdir "$tmpdir/status"
./generate --outdir "$tmpdir/status-security" --dburl postgresql:///mirror-status-security

mkdir -p "$TARGET"
rsync -av "$tmpdir"/* "$TARGET"/ --delete

if command -v static-update-component > /dev/null; then
  static-update-component mirror-master.debian.org
fi

if ! [ -e "$BTS_STATE_FILE" ] || [ "$(stat --format=%Y "$BTS_STATE_FILE" )" -le "$(( $(date +%s) - $BTS_STATE_AGE ))" ]; then
  ./get-bug-status | sponge "$BTS_STATE_FILE"
fi
