"""Add TraceFileList for constructing hierarchy

Revision ID: 9611b88d8eff
Revises: e073428f5fc7
Create Date: 2017-02-12 00:01:54.232201

"""

# revision identifiers, used by Alembic.
revision = '9611b88d8eff'
down_revision = 'e073428f5fc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracefilelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirrorcheckresult_id', sa.Integer(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=False),
    sa.Column('traces', sa.String(), nullable=False),
    sa.Column('traces_last_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mirrorcheckresult_id'], ['mirrorcheckresult.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mirrorcheckresult_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracefilelist')
    ### end Alembic commands ###
