"""Re-create database

Revision ID: ab9e51392d62
Revises: 
Create Date: 2017-02-12 21:27:21.269246

"""

# revision identifiers, used by Alembic.
revision = 'ab9e51392d62'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirrorcheckresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=False),
    sa.Column('last_noerror', sa.DateTime(), nullable=True),
    sa.Column('trace_master_timestamp', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('warning', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site')
    )
    op.create_table('tracefilelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirrorcheckresult_id', sa.Integer(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=False),
    sa.Column('traces', sa.String(), nullable=False),
    sa.Column('traces_last_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mirrorcheckresult_id'], ['mirrorcheckresult.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mirrorcheckresult_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracefilelist')
    op.drop_table('mirrorcheckresult')
    op.drop_table('globalinfo')
    ### end Alembic commands ###
