"""Add GlobalInfo table with last_test

Revision ID: e073428f5fc7
Revises: 7fa13518533a
Create Date: 2017-02-11 10:28:15.475507

"""

# revision identifiers, used by Alembic.
revision = 'e073428f5fc7'
down_revision = '7fa13518533a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('globalinfo')
    ### end Alembic commands ###
